const express = require('express')
const router = express.Router()
const controller = require('../controllers/user_controller')
const auth = require('../middleware/auth')
const validator = require('../middleware/validation')
router.post('/user/login', validator.validateSignin, controller.loginUser)
router.post('/user/logout', auth, controller.logoutUser)
router.post('/user/signup', validator.validateSignup, controller.signUpUser)
router.get('/user/me', auth, controller.getProfile)
router.patch('/user/me', validator.validateUpdateProfile, auth, controller.updateProfile)
router.delete('/user/me', auth, controller.deleteProfile)
router.post('/user/logoutAll', auth, controller.logoutAllUser)
module.exports = router